using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoBolt.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddIdentityTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Users\";");

            // Drop legacy columns that were left over from when the table was renamed from 'Users' to 'AspNetUsers'
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" DROP COLUMN IF EXISTS \"Role\";");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" DROP COLUMN IF EXISTS \"CreatedAt\";");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" DROP COLUMN IF EXISTS \"UpdatedAt\";");

            // Safely add column only if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='Customers' AND column_name='UserId') THEN
                        ALTER TABLE ""Customers"" ADD ""UserId"" integer;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetRoles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(256),
                    ""NormalizedName"" character varying(256),
                    ""ConcurrencyStamp"" text,
                    CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetUsers"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FullName"" text NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""UserName"" character varying(256),
                    ""NormalizedUserName"" character varying(256),
                    ""Email"" character varying(256),
                    ""NormalizedEmail"" character varying(256),
                    ""EmailConfirmed"" boolean NOT NULL,
                    ""PasswordHash"" text,
                    ""SecurityStamp"" text,
                    ""ConcurrencyStamp"" text,
                    ""PhoneNumber"" text,
                    ""PhoneNumberConfirmed"" boolean NOT NULL,
                    ""TwoFactorEnabled"" boolean NOT NULL,
                    ""LockoutEnd"" timestamp with time zone,
                    ""LockoutEnabled"" boolean NOT NULL,
                    ""AccessFailedCount"" integer NOT NULL,
                    CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetRoleClaims"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""RoleId"" integer NOT NULL,
                    ""ClaimType"" text,
                    ""ClaimValue"" text,
                    CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"")
                        REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetUserClaims"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""ClaimType"" text,
                    ""ClaimValue"" text,
                    CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetUserLogins"" (
                    ""LoginProvider"" text NOT NULL,
                    ""ProviderKey"" text NOT NULL,
                    ""ProviderDisplayName"" text,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
                    CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetUserRoles"" (
                    ""UserId"" integer NOT NULL,
                    ""RoleId"" integer NOT NULL,
                    CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
                    CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"")
                        REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetUserTokens"" (
                    ""UserId"" integer NOT NULL,
                    ""LoginProvider"" text NOT NULL,
                    ""Name"" text NOT NULL,
                    ""Value"" text,
                    CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
                    CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
            ");

            // Indexes - all safe with IF NOT EXISTS
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AspNetRoleClaims_RoleId"" ON ""AspNetRoleClaims"" (""RoleId"");");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"") WHERE ""NormalizedName"" IS NOT NULL;");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AspNetUserClaims_UserId"" ON ""AspNetUserClaims"" (""UserId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AspNetUserLogins_UserId"" ON ""AspNetUserLogins"" (""UserId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AspNetUserRoles_RoleId"" ON ""AspNetUserRoles"" (""RoleId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"") WHERE ""NormalizedUserName"" IS NOT NULL;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "Customers");

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    PasswordHash = table.Column<string>(type: "text", nullable: false),
                    Phone = table.Column<string>(type: "text", nullable: false),
                    Role = table.Column<int>(type: "integer", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });
        }
    }
}
